# Shell variables
# Generated by 'wal'
wallpaper='/home/bruno/Pictures/wallpapers/wallpaper_4.jpg'

# Special
background='#022A38'
foreground='#93c7c7'
cursor='#93c7c7'

# Colors
color0='#022A38'
color1='#5D4C70'
color2='#8B3678'
color3='#39976E'
color4='#36688D'
color5='#A5348C'
color6='#B15298'
color7='#93c7c7'
color8='#668b8b'
color9='#5D4C70'
color10='#8B3678'
color11='#39976E'
color12='#36688D'
color13='#A5348C'
color14='#B15298'
color15='#93c7c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
