# Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
#
# Theme Elements & Colors for Hyprland.

# Elements
$hypr_border_size = 2
$hypr_gaps_in = 5
$hypr_gaps_out = 10
$hypr_gaps_ws = -10
$hypr_rounding = 0
$groupbar_font_family = Iosevka
$groupbar_font_size = 10

# Colors
$gradient_angle = 45deg
$active_border_col_1 = 0xFF36688D
$active_border_col_2 = 0xFF5D4C70
$inactive_border_col_1 = 0xFF033c50
$inactive_border_col_2 = 0xFF044e69
$active_shadow_col = 0x66000000
$inactive_shadow_col = 0x66000000
$group_border_active_col = 0xFF8B3678
$group_border_inactive_col = 0xFF39976E
$group_border_locked_active_col = 0xFF5D4C70
$group_border_locked_inactive_col = 0xFF36688D
$groupbar_text_color = 0xFF93c7c7
