## Colors configuration
[colors]
alpha=1.0
foreground=93c7c7
background=022A38

## Normal/regular colors (color palette 0-7)
regular0=022A38  # black
regular1=5D4C70  # red
regular2=8B3678  # green
regular3=39976E  # yellow
regular4=36688D  # blue
regular5=A5348C  # magenta
regular6=B15298  # cyan
regular7=93c7c7  # white

## Bright colors (color palette 8-15)
bright0=668b8b   # bright black
bright1=5D4C70   # bright red
bright2=8B3678   # bright green
bright3=39976E   # bright yellow
bright4=36688D   # bright blue
bright5=A5348C   # bright magenta
bright6=B15298   # bright cyan
bright7=93c7c7   # bright white
