#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## launch terminal with alt config

# Get Colors
DIR="$HOME/.config/hypr"
background="`cat $DIR/rofi/shared/colors.rasi | grep 'background:' | cut -d':' -f2 | tr -d ' '\;`"
accent="`cat $DIR/rofi/shared/colors.rasi | grep 'selected:' | cut -d':' -f2 | tr -d ' '\;`"

CONFIG="$HOME/.config/hypr/foot/foot.ini"

if [ "$1" == "-f" ]; then
	foot --app-id='foot-float' --config="$CONFIG"
elif [ "$1" == "-F" ]; then
	foot --fullscreen --app-id='foot-full' --font="Iosevka Nerd Font:size=14" --override=pad=35x35 --config="$CONFIG"
elif [ "$1" == "-s" ]; then
	foot --app-id='foot-float' --config="$CONFIG" \
	--window-size-pixels=$(slurp -b ${background:1}CC -c ${accent:1}ff -s ${accent:1}0D -w 2 -f "%wx%h")
else
	foot --config="$CONFIG" ${@}
fi
